name: Deployment notifications to Slack

on:
  deployment_status
jobs:
  pr_duplicator:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Deployment Status Notifications to Slack
      uses: citizenos/github-action-deployment-status-notifier-slack@master
      with:
        slack-incoming-webhook-url: ${{secrets.SLACK_INCOMING_WEBHOOK_URL}}
        states: 'pending, success, failure, error'
